### ISSUE TITLE
Node modal needs restructuring 

### ISSUE THREAD

**Issue by cyberorg** [ketan/paragliding-meshmap#59]
Save precious vertical space on the mobile device so user does not have to scroll to see what needs only one glance.

![Screenshot at 2024-09-04 12-03-12](https://github.com/user-attachments/assets/d611d230-81c0-49a9-b494-58b79eb9dee0)

**Comment by ketan** [comment]
Fixed.

Old version:

<img width="382" alt="image" src="https://github.com/user-attachments/assets/8941b82d-751c-433c-9e95-d32ed24c583d">

New version:
<img width="392" alt="image" src="https://github.com/user-attachments/assets/724e6f57-c6b9-40ed-bacc-f0d7df58ca49">
