### ISSUE TITLE
Graph needs refresh

### ISSUE THREAD

**Issue by cyberorg** [ketan/paragliding-meshmap#76]
Opening “Details” on one node and then opening another node’s shows previous node’s graph. 
![6437aec1-ba0f-4b37-ae60-68712f8eea9f](https://github.com/user-attachments/assets/2005d266-1601-4d22-9244-548ba0181a18)
![IMG_3654](https://github.com/user-attachments/assets/15f47283-e197-4550-9d0e-7deeabf43629)

**Comment by cyberorg** [comment]
Related to https://github.com/ketan/paragliding-meshmap/issues/47

**Comment by ketan** [comment]
@cyberorg - this change is deployed. Please let me know if you're still seeing issues
