### ISSUE TITLE
Filter list

### ISSUE THREAD

**Issue by cyberorg** [ketan/paragliding-meshmap#97]
Nodes whose data should not be forwarded to maps.

Alft Aloft https://live.paratracker.in/?nodeId=1129866660
BU Blue Umbrella https://live.paratracker.in/?nodeId=3662845056
MD Maheshwari Devi https://live.paratracker.in/?nodeId=4201492460
BD Bhambhori Devi https://live.paratracker.in/?nodeId=862597568
360 https://live.paratracker.in/?nodeId=862574268
D1 Dharamshala1 https://live.paratracker.in/?nodeId=3662843700

**Comment by ketan** [comment]
Closed via 529b7054a715ded1907f180b3744382a4d3f153e
